name: 'Install botsay'
description: 'installs botsay'
runs:
  using: "composite"
  steps:
    - run: |
        curl -s -o botsay https://custom-packages.faculty.net/botsay-0.1.0
        chmod +x botsay
        sudo mv botsay /bin/botsay
      shell: bash
